### ISSUE TITLE
Insert query

### ISSUE THREAD

**Issue by shivsuthanmhub** [nolanlawson/cordova-prepopulated-database-demo#1]
Hi ,

I tried below snippet for INSERT But it is not handling the blog. But the SELECT snippet working fine.

Any Suggestions on this ?

```
angular.module('starterApp.UserTwoController', [])

.controller('UserTwoCtrl', function($scope,$rootScope) {



            var db = sqlitePlugin.openDatabase('RoomieData.db');
            db.readTransaction(function (txn) {

                               txn.executeSql('SELECT * FROM UserOneTable', [], function (tx, res) {
                                              alert('Successfully read from pre-populated DB:');
                                              alert(JSON.stringify(res.rows.item(0)));



                                              });
                               });


            $scope.userTwoDetails = {};

            var spendType, spendAmount, spendDate, spendNote;

            $scope.doSubmitUserTwoData = function () {

            spendType = $scope.userTwoDetails.spendType;
            spendAmount = $scope.userTwoDetails.spendAmount;
            spendDate = $scope.userTwoDetails.spendDate;
            spendNote = $scope.userTwoDetails.spendNote;

            var db = sqlitePlugin.openDatabase('RoomieData.db');

            var query = "INSERT INTO UserTwoTable (spendType,spendAmount,spendDate,spendNote) VALUES (?,?,?,?)";

            alert(query);

            db.readTransaction (function (txn)  {

                                alert('readTransaction');

                                txn.executeSql(query, [spendType,spendAmount,spendDate,spendNote], function (tx, res) {

                                               alert(tx);
                                               alert(res);

                                               });


                                });


            };


            });
```

**Comment by nolanlawson** [comment]
Hi @shivsuthanmhub, you cannot do an `INSERT` inside of a `readTransaction`. You'll have to use a normal `transaction` for that.

Hope that helps, if not, please open another issue or respond here, cheers.

**Comment by shivsuthanmhub** [comment]
Wow, great thanks, bro @nolanlawson 
After inserting how can I get the updated DB path? But I can able to get the data using code. For understanding, I'm asking you file path.

**Comment by nolanlawson** [comment]
It's explained in this repo: https://github.com/nolanlawson/cordova-plugin-sqlite-2#where-is-data-stored

**Comment by shivsuthanmhub** [comment]
Hi @nolanlawson - while i was asked the above questions, I was concentrated my application only for iOS but now a days I started and managing the application for Android as well but the same Database code which works in iOS its not performing in Android. 

If you've any suggestions in this please let me know.

**Comment by nolanlawson** [comment]
Sorry, without any more detail I can't really provide guidance. Is there an error message? what are you trying to do exactly?

Also if you're directly manipulating files, you may want to look at the Cordova File API: https://github.com/apache/cordova-plugin-file

**Comment by nolanlawson** [comment]
Oh I see you opened #2
