### ISSUE TITLE
iOS Vs Android 

### ISSUE THREAD

**Issue by shivsuthanmhub** [nolanlawson/cordova-prepopulated-database-demo#2]
Hi @nolanlawson - while i was asked the plugin Db related questions earlier, I was concentrated my application only for iOS but now a days I started and managing the application for Android as well but the same Database code which works in iOS its not performing in Android.

If you've any suggestions in this please let me know.

**Comment by shivsuthanmhub** [comment]
As well, I did this below sample 
https://github.com/nolanlawson/cordova-prepopulated-database-demo

But the actual db status printed in iOS but not in Android.

**Comment by shivsuthanmhub** [comment]
<img width="423" alt="screen shot 2016-07-13 at 10 36 41 pm" src="https://cloud.githubusercontent.com/assets/11000006/16812384/79ddd2fa-494a-11e6-8f8d-f1b85db11efd.png">

**Comment by shivsuthanmhub** [comment]
Working iOS Example - The data received from existing code flow in iOS

<img width="432" alt="screen shot 2016-07-13 at 10 37 55 pm" src="https://cloud.githubusercontent.com/assets/11000006/16812672/cf85c72a-494b-11e6-9908-bc2688db249f.png">

Not able to handling in Android 

![img-20160713-wa0003 jpg](https://cloud.githubusercontent.com/assets/11000006/16812717/025033f2-494c-11e6-9c9d-fb1a3ff3831c.jpeg)

Suggest some ideas to access the Db in android as well @nolanlawson

**Comment by nolanlawson** [comment]
Can you connect to the Android device using https://developers.google.com/web/tools/chrome-devtools/debug/remote-debugging/remote-debugging ? The error could be literally anything; it's hard to tell.

**Comment by shivsuthanmhub** [comment]
Yes @nolanlawson I can able to connect and run the application in my device using the mentioned steps, But the thing is the Db file not connected. I don't know exactly I need to tell the Db path or not ?

Anything else ? I need to do for connecting existing database in android.

**Comment by shivsuthanmhub** [comment]
@nolanlawson the Db file connected in Android version 5 and above series I guess, It's working fine in 5 and above. And not able to handled in 4 series. Thanks @nolanlawson

**Comment by nolanlawson** [comment]
I'm sorry, I'm not understanding - are you saying that the demo app (https://github.com/nolanlawson/cordova-prepopulated-database-demo) doesn't work in Android, or that your own personal app doesn't work in Android? I wrote the demo app myself and tested it; it worked in Android, although maybe something changed in Ionic/Cordova/etc. that broke it.

**Comment by shivsuthanmhub** [comment]
@nolanlawson I tried your demo app as well my own app, But both of the apps are working fine in Android 5 series and above. (Earlier I tried android version 4.0 series - It was not worked)

**Comment by nolanlawson** [comment]
Yes, I'm using Promises in the sample app, so you would need an ES5/ES6 shim in Android 4.0.

Please let me konw if you can provide more details, because based on the screenshots and description, it's impossible for me to say what the problem is. A small test case to reproduce (e.g. a sample app) would be extremely helpful.

**Comment by tariqgill** [comment]
i have an issue this ios, data is working in ios simulator but not showing in my ios device, tested in ios 10 and 11. it is may be with some ios db location, what is the actual path

**Comment by nolanlawson** [comment]
closing old issues, please reopen if this is still a problem
